### ISSUE TITLE
Web Deployment Issues

### ISSUE THREAD

**Issue by chepkok3** [tsheporamantso/Setup-Mobile-Project#12]
Well done on trying to replicate the Figma design, especially on the background images and the general appearance of the page.

Here are some of the issues that you can try to work on and improve the project:
-Check on the width alignment of the header and footer sections. They have slightly shifted to the left but maybe you can try to make them cover the width of the document. 
-Kindly also check on the alignment of the cards section. Try to make them centered and almost as in the Figma design.

Optional suggestions:
-Please try to re-check the source path of the images and see if you can remove the space in the image names to see if it can solve the problem.

**Comment by tsheporamantso** [comment]
Issues resolved as requested thank you.

**Comment by chepkok3** [comment]
Thank you🙏.
