### ISSUE TITLE
Solving Opening Button Page Screen and Media Queries

### ISSUE THREAD

**Issue by otmanTR** [tsheporamantso/Setup-Mobile-Project#7]
- On @media Querty requirement the min size of screen should be 768px.
- For semantic reasons instead of heading have a div as a container I suggest you to use footer element.
- The codes look very clear in HTML.
- On Media Query when working on CSS file always use % for values like width, margin etc.

**Comment by tsheporamantso** [comment]
Thank you issues are resolved.
